# Generated by Django 5.1.2 on 2024-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='std_data',
            name='course',
            field=models.CharField(default='B.Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='std_data',
            name='fee',
            field=models.IntegerField(default=10000),
        ),
    ]
